# Generated by Django 5.2.4 on 2025-11-29 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('enrollment', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date when the class is scheduled')),
                ('title', models.CharField(help_text='Class title/topic', max_length=200)),
                ('description', models.TextField(help_text='Class agenda and topics to be covered')),
                ('meet_link', models.URLField(help_text='Google Meet link for the class')),
                ('scheduled_time', models.TimeField(help_text='Scheduled start time')),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Expected duration in minutes')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this class')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, help_text='Leave blank for classes available to all enrolled students', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_classes', to='courses.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Class',
                'verbose_name_plural': 'Daily Classes',
                'db_table': 'daily_classes',
                'ordering': ['-date', '-scheduled_time'],
            },
        ),
    ]
